
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: 'sentry'
    static_configs:
    - targets: ['[2001:bc8:47a0:640::1]:9790']
    scrape_interval: 5m
    scrape_timeout: 4m
  
  - job_name: 'Nginx'
    static_configs:
    - targets: ['47.102.210.24:9113']
      labels:
        instance: 'nginx-wxiou'
    - targets: ['47.102.210.24:9114']
      labels:
        instance: 'nginx-ioku'
  - job_name: 'MongoDB'
    static_configs:
    - targets: ['[2001:bc8:47a0:640::1]:9217']
      labels:
        instance: 'azure-hongkong-244'
    - targets: ['[2001:bc8:47a0:640::1]:9218']
      labels:
        instance: 'aws-singapore-1204'
    - targets: ['[2001:bc8:47a0:640::1]:9219']
      labels:
        instance: 'google-taiwan-238'
    - targets: ['[2001:bc8:47a0:640::1]:9221']
      labels:
        instance: 'azure-netherlands-1205-virmach'
    - targets: ['[2001:bc8:47a0:640::1]:9220']
      labels:
        instance: 'google-tokyo-09'    
    - targets: ['[2001:bc8:47a0:640::1]:9222']
      labels:
        instance: 'aws-seoul-163'  
  - job_name: 'Linux'
    static_configs:
    - targets: ['146.56.153.99:9100']
      labels:
        instance: 'Oracle-Arm'
    - targets: ['193.123.251.169:9100']
      labels:
        instance: 'Oracle-Seoul-01'
    - targets: ['140.238.21.152:9100']
      labels:
        instance: 'Oracle-Seoul-02'
    - targets: ['124.156.141.223:9100']
      labels:
        instance: 'Tencent-hk'
    - targets: ['20.205.41.204:9100']
      labels:
        instance: 'Azure-01'
    - targets: ['47.102.210.24:9100']
      labels:
        instance: '	Aliyun-01'
    - targets: ['139.155.253.244:9100']
      labels:
        instance: 'Tencent-cd'
    - targets: ['47.100.104.162:9100']
      labels:
        instance: 'Aliyun-02'
    - targets: ['116.63.152.214:9100']
      labels:
        instance: 'HuaWei'
    - targets: ['[2001:bc8:47a0:640::1]:9100']
      labels:
        instance: 'Scaleway'
    - targets: ['194.87.236.155:9100']
      labels:
        instance: 'Ruvds'
    - targets: ['20.243.81.253:9100']
      labels:
        instance: 'Azure-02'
    - targets: ['20.239.77.86:9100']
      labels:
        instance: 'Azure-03'
    - targets: ['20.205.61.150:9100']
      labels:
        instance: 'Azure-04'
